### ISSUE TITLE
Cannot bundle on Windows

### ISSUE THREAD

**Issue by ksyrytczyk** [dailymotion/vast-client-js#113]
Hi,

I hit a snag with the project bundling on Windows when running command:

> npm run-script bundle

``` bash
> vast-client@1.3.8 bundle C:\xampp\htdocs\vast-client-js
> browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js

C:\xampp\htdocs\vast-client-js\node_modules\shell-quote\index.js:16
    return s.match(/(['"])((\\\1|[^\1])*?)\1|(\\ |\S)+/g)
             ^

TypeError: s.match is not a function
    at exports.parse (C:\xampp\htdocs\vast-client-js\node_modules\shell-quote\index.js:16:14)
    at C:\xampp\htdocs\vast-client-js\node_modules\browserify\bin\args.js:174:23
    at Array.forEach (native)
    at module.exports (C:\xampp\htdocs\vast-client-js\node_modules\browserify\bin\args.js:173:10)
    at Object.<anonymous> (C:\xampp\htdocs\vast-client-js\node_modules\browserify\bin\cmd.js:6:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Krzysztof\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "bundle"
npm ERR! node v6.3.1
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! vast-client@1.3.8 bundle: `browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vast-client@1.3.8 bundle script 'browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vast-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vast-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vast-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\vast-client-js\npm-debug.log
```

My environment is:
- Windows 7 Pro (64x)
- Node v6.3.1
- NPM v3.8.7

**Comment by michaelvial** [comment]
Hi,

If you update `browserify` to `13.1.0` in the `package.json` file, does the build work?

**Comment by ksyrytczyk** [comment]
Unfortunately not.

I also tried update `coffee-script`  to 1.10.0, and `xmldom` to 0.1.22.

Now I got:
```
> vast-client@1.3.8 bundle C:\xampp\htdocs\vast-client-js
> browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn coffee ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Krzysztof\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "bundle"
npm ERR! node v6.3.1
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! vast-client@1.3.8 bundle: `browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vast-client@1.3.8 bundle script 'browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vast-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -s DMVAST -c 'coffee -scb' --extension=.coffee src/index.coffee -o vast-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vast-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vast-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\vast-client-js\npm-debug.log
```

**Comment by michaelvial** [comment]
Alright, I think I've found why the build doesn't work on Windows. When bundling all `.coffee` files with `browserify`, we use the option `-c` (`--command`) to transform `.coffee` into `.js` files. My guess is `browserify` probably spawns `coffee` child processes for doing that. Unfortunately this requires some specific code in order to work on Windows, according to: https://github.com/jashkenas/coffeescript/issues/3371

But there is a way to build the vast-client on Windows, we just have to split the build command
``` bash
# With browserify 13.1.0
# Transpile all src/**/*.coffee files into lib/**/*.js
coffee --compile --output lib/ src/
# Bundle .js files
browserify -s DMVAST --extension=.js lib/index.js -o vast-client.js
```

**Comment by ksyrytczyk** [comment]
Great, it works now. 

Please look at #114 if it's ok.

Thank you very much for help!
