### ISSUE TITLE
Error: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by dsilhavy** [dailymotion/vast-client-js#180]
Hi,
I am trying to use the library as a node module, but it looks like https is not supported. Do I need to plug in my own HTTP handler to deal with https?
The error stack:
`Error: Protocol "https:" not supported. Expected "http:"
 at new ClientRequest (_http_client.js:55:11)
    at Object.exports.request (http.js:31:10)
    at Object.exports.get (http.js:35:21)
    at Function.NodeURLHandler.get (node_modules/vast-client/dist/urlhandlers/node.js:35:20)
    at Function.URLHandler.get (node_modules/vast-client/dist/urlhandler.js:27:51)
    at Function.VASTParser._parse (node_modules/vast-client/dist/parser.js:102:25)
    at Function.VASTParser.parse (node_modules/vast-client/dist/parser.js:66:19)
    at Function.VASTClient.get (node_modules/vast-client/dist/client.js:56:25)
    at VastHandler.get (handler/VastHandler.js:36:19)
    at Context.<anonymous> (test/handler/VastTest.js:16:15)`

**Comment by michaelvial** [comment]
Hi @dsilhavy,
I confirm, the `Node.js` URLHandler only support `http` protocole.
You gonna have to use your own URLHandler to deal with both cases. Or, if you feel confident, you can make a PR to improve the default URLHandler.

**Comment by dsilhavy** [comment]
@michaelvial Thanks for the quick response. For now I solved the problem by using my own URLHandler. For everyone who encounters the same problem my source code:
```javascript
const DMVAST = require('vast-client');
const Q = require('q');
const requestify = require('requestify');
const DOMParser = require('xmldom').DOMParser;

class VastHandler {

  constructor() {
    this.urlHandler = {
      supported: function () {
        return true;
      },
      get: function (url, options, cb) {
        if (!url) {
          cb(new Error('Invalid URL'));
        }
        requestify.get(url, {
          redirect: true
        })
          .then((result) => {
            cb(null, new DOMParser().parseFromString(result.body));
          })
          .catch((error) => {
            cb(error);
          });

      }
    }
  }

  get(url) {
    const q = Q.defer();
    const options = { urlhandler: this.urlHandler };

    DMVAST.client.get(url, options, function (response, error) {
      if (error) {
        q.reject(error);
      } else {
        q.resolve(response);
      }
    });

    return q.promise;
  }
}

module.exports = VastHandler;

```

**Comment by michaelvial** [comment]
Thx for the example. I'll let this issue open until we update the Node URLHandler.
