### ISSUE TITLE
XHRURLHandler:  (0) error

### ISSUE THREAD

**Issue by evrencoskun** [dailymotion/vast-client-js#424]
Hi for some reason, getting "XHRURLHandler:  (0)" error. 
```
Error: XHRURLHandler:  (0)
    at ee (https://jfgxfo.csb.app/src/vast-client-browser.min.js:1391:7)

    at XMLHttpRequest.i.onerror (https://jfgxfo.csb.app/src/vast-client-browser.min.js:1410:18)
```

I created a [demo ](https://codesandbox.io/s/vast-client-fetching-demo-jfgxfo?file=/src/index.js) on Codesandbox.io. So you can see the related error.

Thanks.

**Comment by ZacharieTFR** [comment]
Hello @evrencoskun,

I cannot reproduce on your test page. 
Here the parsed ad I got on your demo:
```
{
  "ads": [
    {
      "id": "1234567",
      "sequence": null,
      "adType": null,
      "adServingId": null,
      "categories": [],
      "expires": null,
      "viewableImpression": [],
      "system": {
        "value": "GDFP",
        "version": null
      },
      "title": "Linear VPAID Example",
      "description": "Vpaid Linear Video Ad",
      "advertiser": null,
      "pricing": null,
      "survey": null,
      "errorURLTemplates": [
        "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=videoplayfailed[ERRORCODE]",
        "http://www.example.com/error"
      ],
      "impressionURLTemplates": [
        {
          "id": null,
          "url": "https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsu_WHAW_qrXEb_qHy8P72qEMpUidzVLPtpQ0Smf5qydRX_DzExXrSjlXeFKdtQIRqo9y3q5SSZ6xBAa3H5I35vk4LiAhvQ21kL3VBS88QsJ1gKezzbOzQchOlAkOeqMp9vjfQqlc_2xkYM0YLZY5mgflZAOus3HAkW-ysjKkoNBZt0DFLQ8b3bnzZFO8TrnMpoeO_YzTys9Pyq0vX024EVjNLkQnRnRDghxjNRZ7nHmgpx2njhnB42gnnTKmibzuAveMViYwe5m5kWeedi-un8DN1KGMiC5um7FwlA5VkiUnIl68mTt_7QspDQXgPHjB5YCTZXkDMpw&sig=Cg0ArKJSzIs7dLJywpsoEAE&uach_m=[UACH]&adurl="
        },
        {
          "id": null,
          "url": "http://www.example.com/impression"
        }
      ],
      "creatives": [
        {
          "id": "57857370976",
          "adId": null,
          "sequence": "1",
          "apiFramework": null,
          "type": "companion",
          "required": null,
          "variations": [
            {
              "id": "57857370976",
              "adType": "companionAd",
              "width": "300",
              "height": "250",
              "assetWidth": null,
              "assetHeight": null,
              "expandedWidth": null,
              "expandedHeight": null,
              "apiFramework": null,
              "adSlotID": null,
              "pxratio": "1",
              "renderingMode": "default",
              "staticResources": [
                {
                  "url": "https://pagead2.googlesyndication.com/simgad/14568666361913360151",
                  "creativeType": "image/png"
                }
              ],
              "htmlResources": [],
              "iframeResources": [],
              "adParameters": null,
              "xmlEncoded": null,
              "altText": null,
              "companionClickThroughURLTemplate": "https://pubads.g.doubleclick.net/pcs/click?xai=AKAOjsshEUu_445fFGruGmYcNUpBKMSge33irl52lyMv0bn5crIHj8fbS7gSYRuCrbROQzdfdcw8WII9qlRX9oOuHFIGcjwZ5jO3sc3lgBMlgBucnYbjPMdCrkOI5cvDX34MlEbqjDkRkbpm_8EyBGmYTgtNzGksDV1SsmBnjhtq15EtqPfn5U-gxuIWIuqlhIbzTds1Ka3gP3Jt7Zb1O10LHsWPecYEzd_4W7YCqupTgJ2zxW8ZeDbqWVJ8GmUH4TLxIGjtKfwUQkneiGrjqI5f_iPt9Gl4p70lTc4A66BFeKC2vjAIuLa7q8jMnRWdP6DtPM2ad1o4&sig=Cg0ArKJSzNwwiwCVFBs3&fbs_aeid=[gw_fbsaeid]&adurl=https://developers.google.com/interactive-media-ads/docs/vastinspector_dual",
              "companionClickTrackingURLTemplates": [],
              "trackingEvents": {
                "creativeView": [
                  "https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsvPqeH_pviwxF8jCqOYk8zeLCm4cgbm4weRLIv7Lqs5kiQASWJh86kQOlRO72yIShHhCyWWBojxxUtDtH7nkoCUHFjs1obN1Hq_07VCkxMbuJ4BTLvX8tP-wCZaEcix6tqiVQjsne9n8TO9oSVFjxaDkkjWpz2q09f8ZJVlRuz1x3Wg0kEMAnLkERymeAVxai2rAuxwljQ1mScW_pg3hrsuAhiQ4NIE9a2POrfXgyBiqSIljavLduaILF0AarkJbdpR7gvHtC9THoGlTIkUSz7PikvHh_LM80yo3fMIeSl8JRMsvlF_2utxkY6iirZuGQkWDLEypSCz&sig=Cg0ArKJSzDx7g3EHnrfMEAE&uach_m=[UACH]&adurl="
                ]
              }
            }
          ],
          "universalAdIds": []
        },
        {
          "id": null,
          "adId": null,
          "sequence": "1",
          "apiFramework": null,
          "type": "linear",
          "duration": 0,
          "skipDelay": null,
          "mediaFiles": [
            {
              "id": null,
              "fileURL": "https://googleads.github.io/googleads-ima-html5/vpaid/linear/VpaidVideoAd.js",
              "fileSize": 0,
              "deliveryType": "progressive",
              "mimeType": "application/javascript",
              "mediaType": "2D",
              "codec": null,
              "bitrate": 0,
              "minBitrate": 0,
              "maxBitrate": 0,
              "width": 640,
              "height": 480,
              "apiFramework": "VPAID",
              "scalable": null,
              "maintainAspectRatio": null
            }
          ],
          "mezzanine": null,
          "interactiveCreativeFile": null,
          "closedCaptionFiles": [],
          "videoClickThroughURLTemplate": {
            "id": "123",
            "url": "http://google.com"
          },
          "videoClickTrackingURLTemplates": [
            {
              "id": "123",
              "url": "http://www.example.com/click"
            },
            {
              "id": "GDFP",
              "url": "https://pubads.g.doubleclick.net/pcs/click?xai=AKAOjssZZY1U9Y0oknfRjPxJjyTiQ9bxn1omQNct3Rn_xep1SRVyBhd0LNMDDBLfuheJ_PZ-gNEewtaCQ85WT0FegTOXxOd8kVm9OVrUmWlHkdkGA0tu6NbzYcdz6Gy7LV93TrWmw2Fpr_tCMhmbeZRc0JveBtOEHGNIfM1g_ePjyuOd4PwtJBzgVmWcYqXf9tdYq3gYsYmkbFrcWtgwhXfk22yZ7wD-yzpcZWS4SMZCDavk54Rn5gC31Lci6ucdHUAWoobT7P0HIOalt02WJ3_Rgp5PyXootRVGIJuCJtRWTlGzunhCMJJUik-3kQFf_s4CJWCeLDp_&sig=Cg0ArKJSzLqrlZq0f4uEEAE&fbs_aeid=[gw_fbsaeid]&urlfix=1"
            }
          ],
          "videoCustomClickURLTemplates": [],
          "adParameters": "{\"videos\":[ {\"url\":\"https://googleads.github.io/googleads-ima-html5/media/LinearVPAIDCreative.mp4\",\"mimetype\":\"video/mp4\"}]}",
          "icons": [],
          "trackingEvents": {
            "start": [
              "http://www.example.com/start",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=part2viewed&ad_mt=[AD_MT]"
            ],
            "firstQuartile": [
              "http://www.example.com/firstQuartile",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=videoplaytime25&ad_mt=[AD_MT]"
            ],
            "midpoint": [
              "http://www.example.com/midpoint",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=videoplaytime50&ad_mt=[AD_MT]"
            ],
            "thirdQuartile": [
              "http://www.example.com/thirdQuartile",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=videoplaytime75&ad_mt=[AD_MT]"
            ],
            "complete": [
              "http://www.example.com/complete",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=videoplaytime100&ad_mt=[AD_MT]"
            ],
            "mute": [
              "http://www.example.com/mute",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=admute&ad_mt=[AD_MT]"
            ],
            "unmute": [
              "http://www.example.com/unmute",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adunmute&ad_mt=[AD_MT]"
            ],
            "rewind": [
              "http://www.example.com/rewind",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adrewind&ad_mt=[AD_MT]"
            ],
            "pause": [
              "http://www.example.com/pause",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adpause&ad_mt=[AD_MT]"
            ],
            "resume": [
              "http://www.example.com/resume",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adresume&ad_mt=[AD_MT]"
            ],
            "fullscreen": [
              "http://www.example.com/fullscreen",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adfullscreen&ad_mt=[AD_MT]"
            ],
            "creativeView": [
              "http://www.example.com/creativeView",
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=vast_creativeview&ad_mt=[AD_MT]"
            ],
            "acceptInvitation": [
              "http://www.example.com/acceptInvitation"
            ],
            "acceptInvitationLinear": [
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=acceptinvitation&ad_mt=[AD_MT]"
            ],
            "closeLinear": [
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=adclose&ad_mt=[AD_MT]"
            ],
            "exitFullscreen": [
              "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=vast_exit_fullscreen&ad_mt=[AD_MT]"
            ]
          },
          "universalAdIds": []
        }
      ],
      "extensions": [
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "waterfall",
            "fallback_index": "0"
          },
          "children": []
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "geo"
          },
          "children": [
            {
              "name": "Country",
              "value": "FR",
              "attributes": {},
              "children": []
            },
            {
              "name": "Bandwidth",
              "value": "4",
              "attributes": {},
              "children": []
            },
            {
              "name": "BandwidthKbps",
              "value": "20000",
              "attributes": {},
              "children": []
            }
          ]
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "metrics"
          },
          "children": [
            {
              "name": "FeEventId",
              "value": "eBEyYsSOHYC7mLAP25-tuAY",
              "attributes": {},
              "children": []
            },
            {
              "name": "AdEventId",
              "value": "CISP09iHy_YCFeO6UQodaAkIvQ",
              "attributes": {},
              "children": []
            }
          ]
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "ShowAdTracking"
          },
          "children": [
            {
              "name": "CustomTracking",
              "value": null,
              "attributes": {},
              "children": [
                {
                  "name": "Tracking",
                  "value": "https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjstje7WlN8GIhq4kYMCvBB1Es7HPnxzQzxPX5fMQ4QRYRNRVekRQDFZcCpdG63YoK1wdnKlVUtuN9AJgFswvoJwawz0oWHZ5OkZ31JU8qQ8iWeHkrB2ZzJjFe7PqmkaiKbcci9gcPwK_j_lKcd0HWdyCgALTJIW_94dKpLF0JpWrYS54O4R8SJKNzpIq-LWFe7tTdHRLYDyGhqhiOuQoI1LV00z8G_5nRc3QbnN625FbWy_Rpzr7raPo-gOQ66jBZRr9oT8r4qigWlzSJOGC_FozcoaTV3Ysy3F75ZhtDl9PY0FdRMqJUProGhMlZLwBf7mCoaGFfUQctZM&sig=Cg0ArKJSzDfuFBaD8zUNEAE&uach_m=[UACH]&adurl=",
                  "attributes": {
                    "event": "show_ad"
                  },
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "wrapper_info"
          },
          "children": [
            {
              "name": "Duration",
              "value": "00:00:10",
              "attributes": {},
              "children": []
            }
          ]
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "video_ad_loaded"
          },
          "children": [
            {
              "name": "CustomTracking",
              "value": null,
              "attributes": {},
              "children": [
                {
                  "name": "Tracking",
                  "value": "https://pubads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=video_ad_loaded",
                  "attributes": {
                    "event": "loaded"
                  },
                  "children": []
                }
              ]
            }
          ]
        },
        {
          "name": "Extension",
          "value": null,
          "attributes": {
            "type": "heavy_ad_intervention"
          },
          "children": [
            {
              "name": "CustomTracking",
              "value": null,
              "attributes": {},
              "children": [
                {
                  "name": "Tracking",
                  "value": "https://googleads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=heavy_ad_intervention_cpu",
                  "attributes": {
                    "event": "heavy_ad_intervention_cpu"
                  },
                  "children": []
                },
                {
                  "name": "Tracking",
                  "value": "https://googleads.g.doubleclick.net/pagead/interaction/?ai=BjvUXeBEyYoTzHeP1xgLokqDoC-jlr64JAAAAEAEgqN27JjgBWLjpo-iXA2D7iY6DtAqyAQ5qZmd4Zm8uY3NiLmFwcLoBCjcyOHg5MF94bWzIAQXaARdodHRwczovL2pmZ3hmby5jc2IuYXBwL8ACAuACAOoCJS8xMjQzMTkwOTYvZXh0ZXJuYWwvc2luZ2xlX2FkX3NhbXBsZXP4AoTSHoADAZADjAaYA6wCqAMB4AQB0gUGEIjV0LkEkAYBoAYkqAfz0RuoB5bYG6gHqpuxAqgH35-xAtgHAOAHH9IICQiA4YAQEAEYHdgIAoAKBZgLAYAMAdAVAfgWAYAXAQ&sigh=pJKIk97TGqo&label=heavy_ad_intervention_network",
                  "attributes": {
                    "event": "heavy_ad_intervention_network"
                  },
                  "children": []
                }
              ]
            }
          ]
        }
      ],
      "adVerifications": [],
      "blockedAdCategories": [],
      "followAdditionalWrappers": true,
      "allowMultipleAds": false,
      "fallbackOnNoAd": null
    }
  ],
  "errorURLTemplates": [],
  "version": "3.0"
}
```

**Comment by GuillaumeBAECHLER** [comment]
If you see this error, make sure you don't have an ad blocker turned on.

**Comment by evrencoskun** [comment]
Hi @GuillaumeBAECHLER,  I've just tested without running an ad blocker and it worked.

Thanks.
